### ISSUE TITLE
Selection text does not appear in textfield after onSuggestionSelected()?

### ISSUE THREAD

**Issue by andreclinio** [AbdulRahmanAlHamali/flutter_typeahead#118]
Maybe this is not a bug. But a desire feature?!
(I am learning Flutter right now)

Once you comment the navigation action in your " Example1: Navigation", I expect the
see the selected item text inside do textfield. This behavior is quite different from the
"Example 2: Form" -- that works as my expectations...

Any reason for that?

Here goes the simple diff I have locally done.
```
diff --git a/example/lib/material_app.dart b/example/lib/material_app.dart
index f0255cd..d1378bb 100644
--- a/example/lib/material_app.dart
+++ b/example/lib/material_app.dart
@@ -66,8 +66,8 @@ class NavigationExample extends StatelessWidget {
               );
             },
             onSuggestionSelected: (suggestion) {
-              Navigator.of(context).push(MaterialPageRoute(
-                  builder: (context) => ProductPage(product: suggestion)));
+              // Navigator.of(context).push(MaterialPageRoute(
+              //     builder: (context) => ProductPage(product: suggestion)));
             },
           ),
         ],
```

**Comment by mesutaltuncu** [comment]
First define a controller
`final TextEditingController _typeAheadController = TextEditingController();`
then
`TypeAheadField( textFieldConfiguration: TextFieldConfiguration(
                                controller: _typeAheadController,
....`

```
onSuggestionSelected: (suggestion) {
                                setState(() {
                                  _selectedLocation = '${suggestion.name}';
                                });
                                _typeAheadController.text = _selectedLocation;
                              },
```

**Comment by Stephen-Cronin** [comment]
I'm having a problem with this too. I have a controller set up:

 ```
final TextEditingController _teamController = TextEditingController();
```

and assigned:

```
textFieldConfiguration: TextFieldConfiguration(
  controller: _teamController,
```

and have this code for when a suggestions is made:

```
onSuggestionSelected: (suggestion) {
  print(_teamController);
  _teamController.text = suggestion;
  print(_teamController);
}
```

That outputs:

```
I/flutter (31458): TextEditingController#c7014(TextEditingValue(text: ┤Newcas├, selection: TextSelection(baseOffset: 6, extentOffset: 6, affinity: null, isDirectional: false), composing: TextRange(start: 0, end: 6)))
I/flutter (31458): TextEditingController#c7014(TextEditingValue(text: ┤Newcastle United├, selection: TextSelection(baseOffset: -1, extentOffset: -1, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1)))
```

I think that shows that it's worked and the text has been set (although not sure what the TextRange is about?). However, the value never gets displayed in the autocomplete text field:

![autocomplete](https://user-images.githubusercontent.com/1502350/78777962-d4043400-79dd-11ea-93f9-0d9a6d987b98.gif)

Hope I'm just missing something, but I can't seem to make it work. Thanks!

**Comment by Stephen-Cronin** [comment]
Further info: I found that removing the controller entirely meant that instead of the text field being set to empty and losing focus, it retained whatever had been typed so far (not what was selected form the list). Also the `keepSuggestionsOnSuggestionSelected` worked as expected. 

So that approach could be a workaround for people facing this problem, but obviously not as good as setting the field to the selected suggestion so the user knows what has been searched for.

However I found another workaround that will be better for me. I left the controller in (as this didn't work without), but didn't use it to try to set the text field value to the suggestion, as that's clearly not working for me. Instead, I saved the suggestion into a persistent variable (using provider, but presumably widget state would work too), and then used that to display the selected suggestion in the hintText, eg:

```
hintText: thisAppState['searchClub'] == null ? 'Enter exact club name' : thisAppState['searchClub'],
```

The end result is that as soon as a suggestion is selected (and saved into that variable), the hint text replaces the typed text. The user can't then go and edit the text, they have to start again, but at least they can see the currently selected value which is more important.

**Comment by Stephen-Cronin** [comment]
Okay, I've now worked out that I was doing it wrong! 

I had defined the controller in the build widget. When I moved it up above that, into the top level of the stateful widget, it started working as expected, ie setting the controller.text to the suggestion worked properly.

I have noticed a little bit of weirdness with very occasionally the "TextEditingController was used after being disposed" error being thrown, but I can't reliably reproduce that, so I will leave it like this and watch to see if there any further problem.
