### ISSUE TITLE
[Feature request] Scroll to top on focus / onSuggestionsOpened callback

### ISSUE THREAD

**Issue by robindijkhof** [AbdulRahmanAlHamali/flutter_typeahead#175]
On most mobile devices the Keyboard takes up about half the screen size. In this case, the TypeAhead widget is only useful when it is at the top of the screen. Otherwise, the suggestions are barely visible. The picture below is Example 3 with the suggestions open on a Nexus 5X.
![Screenshot 2020-04-19 at 18 28 47](https://user-images.githubusercontent.com/22224763/79693595-cebfa880-826b-11ea-8df4-75cad265aabb.png)

As you can see, the suggestions are not visible and the user has to scroll to the top. I think it would be a nice feature to auto-scroll the TypeAhead to the top of the screen when the suggestions are opened. I'm not sure whether this is possible. Another option would be to have an onSuggestionsOpened callback so developers can do this themself.

**Comment by Stephen-Cronin** [comment]
@robindijkhof - I'm not involved in this project, but sounds like you need to use the direction property. From [the readme](https://github.com/AbdulRahmanAlHamali/flutter_typeahead#customizing-the-growth-direction-of-the-suggestions-list):

>Set autoFlipDirection to true to allow the suggestions list to automatically flip direction whenever it detects that there is not enough space for the current direction.

That said, I'd actually like some options around scrolling on focus. I'm trying to use this on a full screen landscape view, so a) there is very very little space left after the keyboard takes up half of landscape; and b) because it's full screen the keyboard appears over the top of the field that the user has to type into (Flutter bug/feature apparently). It's a pretty poor user experience.

I need to look into whether I can work out a way to scroll it myself on focus, but have something built in would be great.

**Comment by fluttdev** [comment]
Woud appreciate such feature too!
