### ISSUE TITLE
Method not found: 'KeyboardVisibilityController'

### ISSUE THREAD

**Issue by vignesh7501** [AbdulRahmanAlHamali/flutter_typeahead#258]
../../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_typeahead-1.9.1/lib/flutter_typeahead.dart:234:8: Error: Error when reading '../../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_keyboard_visibility-4.0.2/lib/flutter_keyboard_visibility.dart': No such file or directory
    import 'package:flutter_keyboard_visibility/flutter_keyboard_visibility.dart';
           ^
    ../../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_typeahead-1.9.1/lib/flutter_typeahead.dart:742:7: Error: Method not found: 'KeyboardVisibilityController'.
          KeyboardVisibilityController().onChange;
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

It was working fine after I update the package I'm getting the above error. I think the package is didn't install "**flutter_keyboard_visibility**" package properly.

![Screenshot 2020-12-07 at 1 23 36 PM](https://user-images.githubusercontent.com/25900723/101323934-6b809600-388f-11eb-8809-f685f5ef9fd0.png)

**Comment by FRANIAZA** [comment]
I had the same problem, updating flutter_keyboard_visibility to 4.x from 3.x solved the problem.

**Comment by vignesh7501** [comment]
Thank you it's working.

**Comment by vignesh7501** [comment]
I have tried but it's not working.

**Comment by FRANIAZA** [comment]
If you imported flutter_typeahead in your pubspec.yaml, you shouldn't need to import flutter_keyboard_visibility as well, as it is automatically imported in this package.
I had to import it manually because I have a local version of this package, since I needed to customize the state handlig of the textfield.
Anyway, if you remove your flutter_keyboard_visibility import from pubsepc.yaml, and run a 

```flutter clean```

and a

```flutter pub get```

it should autmatically start using the version 4.x of keyboard_visibility and not give you any problems

**Comment by vignesh7501** [comment]
I didn't import flutter_keyboard_visibility in my pubspec.yaml and the issues are coming from the library only
