### ISSUE TITLE
Example file is too empty

### ISSUE THREAD

**Issue by ivofernandes** [AbdulRahmanAlHamali/flutter_typeahead#452]
This is what we can see in the example of pub.dev, the main.dart should be meaningful...

<img width="1206" alt="Screenshot 2023-02-05 at 12 03 41" src="https://user-images.githubusercontent.com/606568/216817603-2b1d2129-b5ca-492f-9df3-b24fe34fcf3a.png">

On the other hand the files of the lib folder have no good reason to be with thousands of lines of code?

**Comment by ivofernandes** [comment]
Do you want a pull request? Would be great to fix it in a period of time where you are not doing big changes, because this file structure stuff can create a lot of git conflicts

**Comment by sjmcdowall** [comment]
@ivofernandes Yes all true.  There are also some warning from pub dev that should be cleaned up one way or another - a PR that fixes all this and the other stuff would be wonderful!

`Package validation found the following potential issues:
* `dart analyze` found the following issue(s):
  Analyzing lib, test, pubspec.yaml...

  warning - lib/src/cupertino_flutter_typeahead.dart:1377:24 - The '!' will have no effect because the receiver can't be null. Try removing the '!' operator. - unnecessary_non_null_assertion
  warning - lib/src/flutter_typeahead.dart:1838:24 - The '!' will have no effect because the receiver can't be null. Try removing the '!' operator. - unnecessary_non_null_assertion
     info - lib/src/cupertino_flutter_typeahead.dart:69:35 - Using a colon as a separator befo[...]dart:8:50 - Using a colon as a separator before a default value is deprecated and will not be supported in language version 3.0 and later. Try replacing the colon with an equal sign. - deprecated_colon_for_default_value
     info - test/flutter_typeahead_test.dart:72:59 - Using a colon as a separator before a default value is deprecated and will not be supported in language version 3.0 and later. Try replacing the colon with an equal sign. - deprecated_colon_for_default_value

  110 issues found.
* 6 checked-in files are ignored by a `.gitignore`.
  Previous versions of Pub would include those in the published package.

  Consider adjusting your `.gitignore` files to not ignore those files, and if you do not wish to
  publish these files use `.pubignore`. See also dart.dev/go/pubignore

  Files that are checked in while gitignored:

  example/android/gradle/wrapper/gradle-wrapper.jar
  example/android/gradlew
  example/android/gradlew.bat
  example/example.iml
  example/ios/Flutter/flutter_export_environment.sh
  example/pubspec.lock`

**Comment by ivofernandes** [comment]
Yes lets wait to see if the @AbdulRahmanAlHamali appears here willing to do the work of accepting a PR and submitting a new package version :)

**Comment by sjmcdowall** [comment]
@ivofernandes -- no reason to wait -- I can merge PRs and publish new versions .. I've been the only one doing it for 2 years now :)

**Comment by ivofernandes** [comment]
Oh so nice, thanks to let me know :) Will do the PR then

**Comment by ivofernandes** [comment]
It's here :) 

https://github.com/AbdulRahmanAlHamali/flutter_typeahead/pull/458

I guess now will be easier for people to understand how the package works, this is a screenshot of the new file tree

<img width="1421" alt="Screenshot 2023-02-17 at 01 42 21" src="https://user-images.githubusercontent.com/606568/219527993-ceb1ab55-953d-48ed-83f1-26b88157ed5a.png">

**Comment by ivofernandes** [comment]
Also added some scripts including one to be easier to publish

**Comment by sjmcdowall** [comment]
Can we close this now @ivofernandes ?

**Comment by ivofernandes** [comment]
Yes
