### ISSUE TITLE
Support for BLoC pattern when building suggestions

### ISSUE THREAD

**Issue by feroldi** [AbdulRahmanAlHamali/flutter_typeahead#46]
Currently, the way `TypeAheadField` et al works is by awaiting on the building of a list of items whenever there is typing interaction:

    TypeAheadField(
      suggestionsCallback: fetchList,
      // ...
    )

This is pretty simple and works well. However, it prevents someone from implementing a BLoC pattern for the building of a suggestion list. Instead of `suggestionCallback`, the constructor could also provide, for example, a `suggestions` field that accepts a `Widget` (such as `BlocBuilder`), so it'd take care to build a `ListView` or something scrollable of the suggestions. Or another solution.

I'd be happy to implement it.

**Comment by sjmcdowall** [comment]
I am not sure what the best solution for BLoC type control makes sense.. the above doesn't seem right to me.. I.e. passing a Widget thing .. the suggestionsCallback doesn't have to be a future and can be just a normal List<String> type.. can't some BLoC thing just update that underlying type and then call setState ?  

Again, not a BLoC guru at all -- so maybe that's not clean.. 

I am also wondering how we should/could handle a Stream instead of a Future .. would your solution handle that?  Maybe we allow a FutureOrStream or something? :)

**Comment by AbdulRahmanAlHamali** [comment]
@feroldi, interested in submitting a pull request?

**Comment by sjmcdowall** [comment]
Since this issue has lagged for quite a while -- I am going to close.  Please feel free to open a new issue / PR when ready.
