### ISSUE TITLE
Styling ListTile spacing between items

### ISSUE THREAD

**Issue by ronniechew** [AbdulRahmanAlHamali/flutter_typeahead#56]
When the font for ListTile's title/subtitle is set to rather small (fontSize 6 or 8), the ListView showing a list of suggestions with huge padding around each ListItem. Can we change this? I've tried changing ListTile.contentPadding but that seems only affecting the Left/Right paddings, and leaving the vertical padding between each ListItem unaffected

![img_20190225_234243](https://user-images.githubusercontent.com/5635018/53349177-763a9700-3957-11e9-8334-b1955cfa5c0d.jpg)
.

**Comment by sjmcdowall** [comment]
I have this question also ...<shrug>

**Comment by KaYBlitZ** [comment]
This looks to be a shortcoming of the ListTile widget. There isn't any vertical padding added by default, which is why changing the padding doesn't affect the vertical space. It is not a problem on TypeAhead's side. I tried returning a Column instead of ListTile and the vertical padding was gone:
```
Column(
                  children: <Widget>[
                    Text(suggestion, textAlign: TextAlign.left,),
                    Text(suggestion, textAlign: TextAlign.left,),
                  ],
                );
```
It doesn't look good, but proves that the padding comes from ListTile. Closing because it is not a problem on our end.
